### ISSUE TITLE
Cannot Load nuxt-fontawesome...

### ISSUE THREAD

**Issue by rlam3** [vaso2/nuxt-fontawesome#1]
https://github.com/Qonfucius/nuxt-fontawesome and this nuxt-fontawesome?

**Comment by rlam3** [comment]
Also the setup and usage is very confusing. Could you consolidate it into one piece? Thanks!

**Comment by rlam3** [comment]
The only way to get it working was to import FontAwesomeIcon again in my component .vue file... Any reason why this may be happening? Thanks! 
```js
import FontAwesomeIcon from '@fortawesome/vue-fontawesome'
export default {
  components: {
    FontAwesomeIcon
  },
}
```

**Comment by vaso2** [comment]
@rlam3 Hi there!
Working example should be like this:
```js
module.exports = {
 /* Some other stuff */

  modules: [
    'nuxt-fontawesome',
     /* Some other modules */
  ],
  fontawesome: {
    imports: [
      {
        set: '@fortawesome/fontawesome-free-solid'
      }
    ]
  },
  build: {
    extend (config) {
       /* Tweak build if needed  */
    }
  },
```
Not inside ` build: {`, like in your example. That's why you got a problem with importing FontAwesomeIcon. Also, big thanks for pointing at my mistakes with docs, fixed that.
Happy coding!

**Comment by heidipowers** [comment]
Hey Vaso2 - thanks so much for creating this plugin!

For anyone who may be playing with the development branch of [vue-fontawesome](https://github.com/FortAwesome/vue-fontawesome/tree/development) you'll get this same error. To fix it the plugin file can be adjusted from:

`import FontAwesomeIcon from '@fortawesome/vue-fontawesome'`

to:

`
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'`

Hoping to save someone else time who may also be poking around at things.

Thanks again!
