### ISSUE TITLE
ssr support? 

### ISSUE THREAD

**Issue by jericopulvera** [vaso2/nuxt-fontawesome#4]
Is ssr supported?

I assumed it is since we're using nuxt but I'm getting these error on page refresh.

> Could not find one or more icon(s) { prefix: 'fas', iconName: 'search' } {}

**Comment by vaso2** [comment]
Yes, SSR is supported. Checked this exact icon, just in case, works fine.
In my case it looks like that:
`<fa :icon="['fas', 'search']" class="md-icon md-icon-font md-theme-default"/>`
Check your config, imports etc.

**Comment by vaso2** [comment]
Found that recent update of Fontawesome to version 5.1 has some breaking changes, I'll make an update ASAP.
