### ISSUE TITLE
Large (13 Kb gzipped) bundle size for just one icon

### ISSUE THREAD

**Issue by korigod** [vaso2/nuxt-fontawesome#5]
Hi, and thank you very much for the project! ❤️

I installed the package, in `nuxt.config.js` added `'nuxt-fontawesome'` to `modules` and
```
fontawesome: {
    component: 'fa'
}
```
to the `module_exports`, then imported just one icon with 
```import { faSyncAlt } from '@fortawesome/free-solid-svg-icons';```
in the component file.

However, `@fontawesome` in my bundle is over 13 Kb gzipped — mainly because of `fontawesome-svg-core/index.es.js`. Have I configured something wrong? I use fresh `nuxt-edge`.

**Comment by vaso2** [comment]
Greetings! 
Thanks for using my plugin. Just made some tests, your config seems to be OK. `fontawesome-svg-core/index.es.js` is fontawesome's common staff, not icons. Adding one more will have a very small impact. To compare results try importing the whole set like 
```import { fab } from '@fortawesome/free-solid-svg-icons';```
Also, I haven't tried nuxt-edge and don't know about possible caveats, but 13kb looks totally fine overall:)
