### ISSUE TITLE
Possible to configure dom watch?

### ISSUE THREAD

**Issue by kevcodez** [vaso2/nuxt-fontawesome#6]
In vue fontawesome it is possible to configure dom watching:

```
import { dom } from '@fortawesome/fontawesome-svg-core'

dom.watch()
```

Is there a way to configure it using this plugin?

**Comment by kevcodez** [comment]
Oh well, I simply put the code above in the component where I need this.

**Comment by francoism90** [comment]
@kevcodez Thanks for your workaround!
